replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: quay.io/btison/cna-ai-review-summarizer
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "906824d"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  portName: http
  port: 8080
  containerPort: 8080

route:
  enabled: false
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

argocd:
  enabled: true
  syncwave: "1"

kafka:
  bootstrapServer: ""
  securityProtocol: ""
  saslMechanism: ""
  clientId: ""
  clientSecret: ""
  topic:
    intake: reviews.processed
    processed: reviews.summary
    review: reviews.summary.review
    error: reviews.summary.errors
  consumerGroup:
    intake: review-summarizer-consumer-grp

mongodb:
  connectionString:
  database:
  collection:
    reviews: reviews
    summary: summary
  username:
  password:

llm:
  summary:
    modelName:
    apiKey:
    baseUrl:
    logRequests: true
    logResponses: true
    temperature: 0.9
    timeout: 180s
    strictJsonSchema: true 