nameOverride: "amq-streams"
fullnameOverride: ""

namespace: openshift-operators

subscription:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operator:
    syncwave: "-2"
